package pe.gob.gdr.access.application.dto.response;

public record FeatureAccessResponse(
        boolean canAccessDashboard,
        boolean canViewAssignments,
        boolean canViewCatalogs,
        boolean canViewIndicators,
        boolean canManageIndicators,
        boolean canViewGoals,
        boolean canManageGoals,
        boolean canViewEvidences,
        boolean canManageEvidences,
        boolean canReviewEvidences,
        boolean canViewFinalEvaluations,
        boolean canManageFinalEvaluations,
        boolean canViewResults,
        boolean canViewDocuments,
        boolean canPrepareDocuments,
        boolean canStartSignatureFlow,
        boolean canRegisterSignatureReturn,
        boolean canRegisterSignedDocuments,
        boolean canViewImprovements,
        boolean canManageImprovements,
        boolean canFollowupImprovements,
        boolean canViewReports,
        boolean canViewNotifications,
        boolean canViewConsents,
        boolean canViewOrhReception,
        boolean canManageUsers,
        // T0-01: permisos GDR participación (ORH funcional, no admin técnico)
        boolean canViewParticipacion,
        boolean canManageParticipacion,
        boolean canViewDistinguidoCandidates,
        boolean canManageDistinguidoRequisites,
        boolean canAssignDistinguido,
        // P0: capacidades normativas nuevas (RPE 068-2020)
        boolean canViewCronograma,
        boolean canEditCronograma,
        boolean canViewSeguimiento,
        boolean canRegistrarSeguimiento,
        boolean canSolicitarConfirmacion,
        boolean canViewConfirmacion,
        boolean canViewCie,
        boolean canResolverCasosCie,
        boolean canViewInformeCierre,
        boolean canGenerarInformeCierre,
        boolean canViewAuditoria
) {
}
