-- OBSOLETO desde V75__extend_institution_branding_company_fields.sql.
--
-- El branding institucional ya no usa columnas BLOB en SEC_INSTITUTION_BRANDING.
-- El logo se carga desde el modulo web de Administracion del sistema y se guarda
-- fisicamente bajo GDR_STORAGE_PATH; la tabla conserva solo la ruta relativa en
-- SEC_INSTITUTION_BRANDING.LOGO_RUTA, junto con LOGO_MIME_TYPE y
-- LOGO_NOMBRE_ORIGINAL.
--
-- No ejecutar este archivo para carga de logos.
