WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

CREATE SEQUENCE SQ_GDR_AUDIT_EVENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE GDR_AUDIT_EVENT (
    ID_AUDIT_EVENT NUMBER(19) NOT NULL,
    EVENT_CODE VARCHAR2(60 CHAR) NOT NULL,
    PRINCIPAL VARCHAR2(120 CHAR),
    DETAIL VARCHAR2(500 CHAR),
    CLIENT_IP VARCHAR2(64 CHAR),
    USER_AGENT VARCHAR2(500 CHAR),
    REQUEST_PATH VARCHAR2(250 CHAR),
    OCCURRED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE GDR_AUDIT_EVENT
    ADD CONSTRAINT PK_GDR_AUDIT_EVENT PRIMARY KEY (ID_AUDIT_EVENT);

CREATE INDEX IX_GDR_AUDIT_EVENT_CODE ON GDR_AUDIT_EVENT (EVENT_CODE);
CREATE INDEX IX_GDR_AUDIT_EVENT_PRINCIPAL ON GDR_AUDIT_EVENT (PRINCIPAL);
CREATE INDEX IX_GDR_AUDIT_EVENT_OCCURRED_AT ON GDR_AUDIT_EVENT (OCCURRED_AT);
