WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

CREATE SEQUENCE SQ_HR_ORG_UNIT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_HR_PERSON START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_GDR_EVALUATION_ASSIGNMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
