WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

CREATE TABLE GDR_VALUE_TYPE (
    ID_VALUE_TYPE NUMBER(19) NOT NULL,
    VALUE_TYPE_CODE VARCHAR2(40 CHAR) NOT NULL,
    VALUE_TYPE_NAME VARCHAR2(100 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(250 CHAR),
    STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE GDR_FORMULA (
    ID_FORMULA NUMBER(19) NOT NULL,
    FORMULA_CODE VARCHAR2(40 CHAR) NOT NULL,
    FORMULA_NAME VARCHAR2(120 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(250 CHAR),
    STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE GDR_SEGMENT (
    ID_SEGMENT NUMBER(19) NOT NULL,
    SEGMENT_CODE VARCHAR2(40 CHAR) NOT NULL,
    SEGMENT_NAME VARCHAR2(120 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(250 CHAR),
    STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);
