WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

ALTER TABLE GDR_VALUE_TYPE
    ADD CONSTRAINT PK_GDR_VALUE_TYPE PRIMARY KEY (ID_VALUE_TYPE);

ALTER TABLE GDR_FORMULA
    ADD CONSTRAINT PK_GDR_FORMULA PRIMARY KEY (ID_FORMULA);

ALTER TABLE GDR_SEGMENT
    ADD CONSTRAINT PK_GDR_SEGMENT PRIMARY KEY (ID_SEGMENT);

ALTER TABLE GDR_VALUE_TYPE
    ADD CONSTRAINT UK_GDR_VALUE_TYPE_CODE UNIQUE (VALUE_TYPE_CODE);

ALTER TABLE GDR_FORMULA
    ADD CONSTRAINT UK_GDR_FORMULA_CODE UNIQUE (FORMULA_CODE);

ALTER TABLE GDR_SEGMENT
    ADD CONSTRAINT UK_GDR_SEGMENT_CODE UNIQUE (SEGMENT_CODE);

ALTER TABLE GDR_VALUE_TYPE
    ADD CONSTRAINT CK_GDR_VALUE_TYPE_STATUS
    CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));

ALTER TABLE GDR_FORMULA
    ADD CONSTRAINT CK_GDR_FORMULA_STATUS
    CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));

ALTER TABLE GDR_SEGMENT
    ADD CONSTRAINT CK_GDR_SEGMENT_STATUS
    CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));

CREATE INDEX IX_GDR_VALUE_TYPE_STATUS ON GDR_VALUE_TYPE (STATUS);
CREATE INDEX IX_GDR_FORMULA_STATUS ON GDR_FORMULA (STATUS);
CREATE INDEX IX_GDR_SEGMENT_STATUS ON GDR_SEGMENT (STATUS);
