WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

ALTER TABLE GDR_INDICATOR
    ADD CONSTRAINT PK_GDR_INDICATOR PRIMARY KEY (ID_INDICATOR);

ALTER TABLE GDR_GOAL
    ADD CONSTRAINT PK_GDR_GOAL PRIMARY KEY (ID_GOAL);

ALTER TABLE GDR_INDICATOR
    ADD CONSTRAINT UK_GDR_INDICATOR_CODE UNIQUE (INDICATOR_CODE);

ALTER TABLE GDR_INDICATOR
    ADD CONSTRAINT FK_GDR_INDICATOR_VALUE_TYPE
    FOREIGN KEY (ID_VALUE_TYPE) REFERENCES GDR_VALUE_TYPE (ID_VALUE_TYPE);

ALTER TABLE GDR_INDICATOR
    ADD CONSTRAINT FK_GDR_INDICATOR_FORMULA
    FOREIGN KEY (ID_FORMULA) REFERENCES GDR_FORMULA (ID_FORMULA);

ALTER TABLE GDR_INDICATOR
    ADD CONSTRAINT FK_GDR_INDICATOR_SEGMENT
    FOREIGN KEY (ID_SEGMENT) REFERENCES GDR_SEGMENT (ID_SEGMENT);

ALTER TABLE GDR_GOAL
    ADD CONSTRAINT FK_GDR_GOAL_ASSIGNMENT
    FOREIGN KEY (ID_ASSIGNMENT) REFERENCES GDR_EVALUATION_ASSIGNMENT (ID_ASSIGNMENT);

ALTER TABLE GDR_GOAL
    ADD CONSTRAINT FK_GDR_GOAL_INDICATOR
    FOREIGN KEY (ID_INDICATOR) REFERENCES GDR_INDICATOR (ID_INDICATOR);

ALTER TABLE GDR_INDICATOR
    ADD CONSTRAINT CK_GDR_INDICATOR_STATUS
    CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));

ALTER TABLE GDR_GOAL
    ADD CONSTRAINT CK_GDR_GOAL_STATUS
    CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));

ALTER TABLE GDR_GOAL
    ADD CONSTRAINT CK_GDR_GOAL_WEIGHT
    CHECK (WEIGHT > 0 AND WEIGHT <= 100);

ALTER TABLE GDR_GOAL
    ADD CONSTRAINT CK_GDR_GOAL_EXPECTED_VALUE
    CHECK (EXPECTED_VALUE > 0);

CREATE INDEX IX_GDR_INDICATOR_VALUE_TYPE ON GDR_INDICATOR (ID_VALUE_TYPE);
CREATE INDEX IX_GDR_INDICATOR_FORMULA ON GDR_INDICATOR (ID_FORMULA);
CREATE INDEX IX_GDR_INDICATOR_SEGMENT ON GDR_INDICATOR (ID_SEGMENT);
CREATE INDEX IX_GDR_INDICATOR_STATUS ON GDR_INDICATOR (STATUS);
CREATE INDEX IX_GDR_GOAL_ASSIGNMENT ON GDR_GOAL (ID_ASSIGNMENT);
CREATE INDEX IX_GDR_GOAL_INDICATOR ON GDR_GOAL (ID_INDICATOR);
CREATE INDEX IX_GDR_GOAL_STATUS ON GDR_GOAL (STATUS);
