WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

CREATE TABLE GDR_ESTADO_EVIDENCIA (
    ID_EVIDENCE_STATUS NUMBER(19) NOT NULL,
    STATUS_CODE VARCHAR2(40 CHAR) NOT NULL,
    STATUS_NAME VARCHAR2(100 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(250 CHAR),
    STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE GDR_EVIDENCIA (
    ID_EVIDENCE NUMBER(19) NOT NULL,
    ID_GOAL NUMBER(19) NOT NULL,
    ID_EVIDENCE_STATUS NUMBER(19) NOT NULL,
    EVIDENCE_TITLE VARCHAR2(180 CHAR) NOT NULL,
    EVIDENCE_DETAIL VARCHAR2(1000 CHAR),
    EXPECTED_DATE DATE,
    STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE GDR_REVISION_EVIDENCIA (
    ID_EVIDENCE_REVIEW NUMBER(19) NOT NULL,
    ID_EVIDENCE NUMBER(19) NOT NULL,
    ID_EVIDENCE_STATUS NUMBER(19) NOT NULL,
    REVIEW_COMMENT VARCHAR2(1000 CHAR),
    REVIEWED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE GDR_ACCION_CORRECTIVA (
    ID_CORRECTIVE_ACTION NUMBER(19) NOT NULL,
    ID_EVIDENCE_REVIEW NUMBER(19) NOT NULL,
    ACTION_DETAIL VARCHAR2(1000 CHAR) NOT NULL,
    ACTION_STATUS VARCHAR2(20 CHAR) DEFAULT 'OPEN' NOT NULL,
    COMPLETED_AT TIMESTAMP(6),
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);
