WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

ALTER TABLE GDR_ESTADO_EVIDENCIA
    ADD CONSTRAINT PK_GDR_ESTADO_EVIDENCIA PRIMARY KEY (ID_EVIDENCE_STATUS);

ALTER TABLE GDR_EVIDENCIA
    ADD CONSTRAINT PK_GDR_EVIDENCE PRIMARY KEY (ID_EVIDENCE);

ALTER TABLE GDR_REVISION_EVIDENCIA
    ADD CONSTRAINT PK_GDR_REVISION_EVIDENCIA PRIMARY KEY (ID_EVIDENCE_REVIEW);

ALTER TABLE GDR_ACCION_CORRECTIVA
    ADD CONSTRAINT PK_GDR_ACCION_CORRECTIVA PRIMARY KEY (ID_CORRECTIVE_ACTION);

ALTER TABLE GDR_ESTADO_EVIDENCIA
    ADD CONSTRAINT UK_GDR_ESTADO_EVIDENCIA_CODE UNIQUE (STATUS_CODE);

ALTER TABLE GDR_EVIDENCIA
    ADD CONSTRAINT FK_GDR_EVIDENCE_GOAL
    FOREIGN KEY (ID_GOAL) REFERENCES GDR_GOAL (ID_GOAL);

ALTER TABLE GDR_EVIDENCIA
    ADD CONSTRAINT FK_GDR_EVIDENCE_STATUS
    FOREIGN KEY (ID_EVIDENCE_STATUS) REFERENCES GDR_ESTADO_EVIDENCIA (ID_EVIDENCE_STATUS);

ALTER TABLE GDR_REVISION_EVIDENCIA
    ADD CONSTRAINT FK_GDR_EVIDENCE_REVIEW_EVIDENCE
    FOREIGN KEY (ID_EVIDENCE) REFERENCES GDR_EVIDENCIA (ID_EVIDENCE);

ALTER TABLE GDR_REVISION_EVIDENCIA
    ADD CONSTRAINT FK_GDR_EVIDENCE_REVIEW_STATUS
    FOREIGN KEY (ID_EVIDENCE_STATUS) REFERENCES GDR_ESTADO_EVIDENCIA (ID_EVIDENCE_STATUS);

ALTER TABLE GDR_ACCION_CORRECTIVA
    ADD CONSTRAINT FK_GDR_CORRECTIVE_ACTION_REVIEW
    FOREIGN KEY (ID_EVIDENCE_REVIEW) REFERENCES GDR_REVISION_EVIDENCIA (ID_EVIDENCE_REVIEW);

ALTER TABLE GDR_ESTADO_EVIDENCIA
    ADD CONSTRAINT CK_GDR_EVIDENCE_STATUS_STATE
    CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));

ALTER TABLE GDR_EVIDENCIA
    ADD CONSTRAINT CK_GDR_EVIDENCE_STATE
    CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));

ALTER TABLE GDR_ACCION_CORRECTIVA
    ADD CONSTRAINT CK_GDR_CORRECTIVE_ACTION_STATUS
    CHECK (ACTION_STATUS IN ('OPEN', 'COMPLETED'));

CREATE INDEX IX_GDR_EVIDENCIA_META ON GDR_EVIDENCIA (ID_GOAL);
CREATE INDEX IX_GDR_EVIDENCIA_ESTADO ON GDR_EVIDENCIA (ID_EVIDENCE_STATUS);
CREATE INDEX IX_GDR_EVIDENCIA_ESTADO_GENERAL ON GDR_EVIDENCIA (STATUS);
CREATE INDEX IX_GDR_REVISION_EVIDENCIA_EVIDENCIA ON GDR_REVISION_EVIDENCIA (ID_EVIDENCE);
CREATE INDEX IX_GDR_REVISION_EVIDENCIA_ESTADO ON GDR_REVISION_EVIDENCIA (ID_EVIDENCE_STATUS);
CREATE INDEX IX_GDR_ACCION_CORRECTIVA_REVISION ON GDR_ACCION_CORRECTIVA (ID_EVIDENCE_REVIEW);
CREATE INDEX IX_GDR_ACCION_CORRECTIVA_ESTADO ON GDR_ACCION_CORRECTIVA (ACTION_STATUS);
