WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

ALTER TABLE GDR_ACCION_CORRECTIVA
    ADD (ID_EVIDENCE NUMBER(19));

UPDATE GDR_ACCION_CORRECTIVA action
SET action.ID_EVIDENCE = (
    SELECT review.ID_EVIDENCE
    FROM GDR_REVISION_EVIDENCIA review
    WHERE review.ID_EVIDENCE_REVIEW = action.ID_EVIDENCE_REVIEW
)
WHERE action.ID_EVIDENCE IS NULL;

MERGE INTO GDR_ACCION_CORRECTIVA target
USING (
    SELECT ID_CORRECTIVE_ACTION
    FROM (
        SELECT
            action.ID_CORRECTIVE_ACTION,
            ROW_NUMBER() OVER (
                PARTITION BY action.ID_EVIDENCE
                ORDER BY action.CREATED_AT DESC, action.ID_CORRECTIVE_ACTION DESC
            ) AS RN
        FROM GDR_ACCION_CORRECTIVA action
        WHERE UPPER(action.ACTION_STATUS) = 'OPEN'
    )
    WHERE RN > 1
) source
ON (target.ID_CORRECTIVE_ACTION = source.ID_CORRECTIVE_ACTION)
WHEN MATCHED THEN
    UPDATE SET
        target.ACTION_STATUS = 'COMPLETED',
        target.COMPLETED_AT = NVL(target.COMPLETED_AT, SYSTIMESTAMP),
        target.UPDATED_AT = SYSTIMESTAMP;

ALTER TABLE GDR_ACCION_CORRECTIVA
    MODIFY (ID_EVIDENCE NOT NULL);

ALTER TABLE GDR_ACCION_CORRECTIVA
    ADD CONSTRAINT FK_GDR_CORRECTIVE_ACTION_EVIDENCE
    FOREIGN KEY (ID_EVIDENCE) REFERENCES GDR_EVIDENCIA (ID_EVIDENCE);

CREATE INDEX IX_GDR_ACCION_CORRECTIVA_EVIDENCIA ON GDR_ACCION_CORRECTIVA (ID_EVIDENCE);

CREATE UNIQUE INDEX UX_GDR_ACCION_CORRECTIVA_OPEN_EVIDENCIA
    ON GDR_ACCION_CORRECTIVA (
        DECODE(UPPER(ACTION_STATUS), 'OPEN', ID_EVIDENCE, NULL)
    );
