WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

DECLARE
    v_index_count NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO v_index_count
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'UX_GDR_ACCION_CORRECTIVA_OPEN_EVIDENCIA';

    IF v_index_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE UNIQUE INDEX UX_GDR_ACCION_CORRECTIVA_OPEN_EVIDENCIA
                ON GDR_ACCION_CORRECTIVA (
                    DECODE(UPPER(ACTION_STATUS), ''OPEN'', ID_EVIDENCE, NULL)
                )';
    END IF;
END;
/
