WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

CREATE SEQUENCE SQ_DOC_TIPO_DOCUMENTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_DOC_PLANTILLA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_DOC_DOCUMENTO_FIRMADO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_DOC_VERSION_DOCUMENTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_DOC_HASH_DOCUMENTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
