WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

ALTER TABLE SEC_USER ADD CONSTRAINT PK_SEC_USER PRIMARY KEY (ID_USER);
ALTER TABLE SEC_ROLE ADD CONSTRAINT PK_SEC_ROLE PRIMARY KEY (ID_ROLE);
ALTER TABLE SEC_USER_ROLE ADD CONSTRAINT PK_SEC_USER_ROLE PRIMARY KEY (ID_USER_ROLE);
ALTER TABLE SEC_REFRESH_TOKEN ADD CONSTRAINT PK_SEC_REFRESH_TOKEN PRIMARY KEY (ID_REFRESH_TOKEN);

ALTER TABLE SEC_USER ADD CONSTRAINT UK_SEC_USER_USERNAME UNIQUE (USERNAME);
ALTER TABLE SEC_USER ADD CONSTRAINT UK_SEC_USER_EMAIL UNIQUE (EMAIL);
ALTER TABLE SEC_ROLE ADD CONSTRAINT UK_SEC_ROLE_CODE UNIQUE (ROLE_CODE);
ALTER TABLE SEC_USER_ROLE ADD CONSTRAINT UK_SEC_USER_ROLE_USER_ROLE UNIQUE (ID_USER, ID_ROLE);
ALTER TABLE SEC_REFRESH_TOKEN ADD CONSTRAINT UK_SEC_REFRESH_TOKEN_VALUE UNIQUE (TOKEN_VALUE);

ALTER TABLE SEC_USER_ROLE
    ADD CONSTRAINT FK_SEC_USER_ROLE_USER
    FOREIGN KEY (ID_USER) REFERENCES SEC_USER (ID_USER);

ALTER TABLE SEC_USER_ROLE
    ADD CONSTRAINT FK_SEC_USER_ROLE_ROLE
    FOREIGN KEY (ID_ROLE) REFERENCES SEC_ROLE (ID_ROLE);

ALTER TABLE SEC_REFRESH_TOKEN
    ADD CONSTRAINT FK_SEC_REFRESH_TOKEN_USER
    FOREIGN KEY (ID_USER) REFERENCES SEC_USER (ID_USER);

ALTER TABLE SEC_USER ADD CONSTRAINT CK_SEC_USER_STATUS
    CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));

ALTER TABLE SEC_USER ADD CONSTRAINT CK_SEC_USER_FAILED_ATTEMPTS
    CHECK (FAILED_ATTEMPTS >= 0);

ALTER TABLE SEC_ROLE ADD CONSTRAINT CK_SEC_ROLE_STATUS
    CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));

ALTER TABLE SEC_USER_ROLE ADD CONSTRAINT CK_SEC_USER_ROLE_STATUS
    CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));

CREATE INDEX IX_SEC_USER_STATUS ON SEC_USER (STATUS);
CREATE INDEX IX_SEC_USER_ROLE_USER ON SEC_USER_ROLE (ID_USER);
CREATE INDEX IX_SEC_USER_ROLE_ROLE ON SEC_USER_ROLE (ID_ROLE);
CREATE INDEX IX_SEC_REFRESH_TOKEN_USER ON SEC_REFRESH_TOKEN (ID_USER);
CREATE INDEX IX_SEC_REFRESH_TOKEN_EXPIRES_AT ON SEC_REFRESH_TOKEN (EXPIRES_AT);
