WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

CREATE TABLE DOC_TIPO_DOCUMENTO (
    ID_TIPO_DOCUMENTO NUMBER(19) NOT NULL,
    CODIGO_TIPO_DOCUMENTO VARCHAR2(40 CHAR) NOT NULL,
    NOMBRE_TIPO_DOCUMENTO VARCHAR2(120 CHAR) NOT NULL,
    DESCRIPCION VARCHAR2(300 CHAR),
    ESTADO VARCHAR2(20 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE DOC_PLANTILLA (
    ID_PLANTILLA NUMBER(19) NOT NULL,
    ID_TIPO_DOCUMENTO NUMBER(19) NOT NULL,
    NOMBRE_PLANTILLA VARCHAR2(150 CHAR) NOT NULL,
    DESCRIPCION VARCHAR2(300 CHAR),
    CLAVE_ARCHIVO VARCHAR2(260 CHAR) NOT NULL,
    NOMBRE_ORIGINAL VARCHAR2(180 CHAR) NOT NULL,
    MIME_TYPE VARCHAR2(120 CHAR) NOT NULL,
    TAMANIO_BYTES NUMBER(19) DEFAULT 0 NOT NULL,
    ESTADO VARCHAR2(20 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE DOC_DOCUMENTO_FIRMADO (
    ID_DOCUMENTO_FIRMADO NUMBER(19) NOT NULL,
    ID_RESULTADO NUMBER(19) NOT NULL,
    ID_TIPO_DOCUMENTO NUMBER(19) NOT NULL,
    NOMBRE_ORIGINAL VARCHAR2(180 CHAR) NOT NULL,
    MIME_TYPE VARCHAR2(120 CHAR) NOT NULL,
    TAMANIO_BYTES NUMBER(19) NOT NULL,
    VERSION_ACTUAL NUMBER(10) DEFAULT 1 NOT NULL,
    CLAVE_ARCHIVO VARCHAR2(260 CHAR) NOT NULL,
    ESTADO VARCHAR2(20 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    USUARIO_CARGA VARCHAR2(120 CHAR) NOT NULL,
    FECHA_CARGA TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_CREACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE DOC_VERSION_DOCUMENTO (
    ID_VERSION_DOCUMENTO NUMBER(19) NOT NULL,
    ID_DOCUMENTO_FIRMADO NUMBER(19) NOT NULL,
    NUMERO_VERSION NUMBER(10) NOT NULL,
    CLAVE_ARCHIVO VARCHAR2(260 CHAR) NOT NULL,
    TAMANIO_BYTES NUMBER(19) NOT NULL,
    USUARIO_REGISTRO VARCHAR2(120 CHAR) NOT NULL,
    FECHA_REGISTRO TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ESTADO VARCHAR2(20 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE DOC_HASH_DOCUMENTO (
    ID_HASH_DOCUMENTO NUMBER(19) NOT NULL,
    ID_DOCUMENTO_FIRMADO NUMBER(19) NOT NULL,
    ID_VERSION_DOCUMENTO NUMBER(19) NOT NULL,
    ALGORITMO_HASH VARCHAR2(30 CHAR) DEFAULT 'SHA-256' NOT NULL,
    VALOR_HASH VARCHAR2(128 CHAR) NOT NULL,
    FECHA_CREACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);
