WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

CREATE SEQUENCE SQ_GDR_ESTADO_OPORTUNIDAD_MEJORA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_GDR_OPORTUNIDAD_MEJORA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_GDR_SEGUIMIENTO_OPORTUNIDAD_MEJORA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
