WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

CREATE TABLE GDR_ESTADO_OPORTUNIDAD_MEJORA (
    ID_ESTADO_OPORTUNIDAD_MEJORA NUMBER(19) NOT NULL,
    CODIGO_ESTADO VARCHAR2(30 CHAR) NOT NULL,
    NOMBRE_ESTADO VARCHAR2(100 CHAR) NOT NULL,
    DESCRIPCION VARCHAR2(250 CHAR),
    ESTADO_REGISTRO VARCHAR2(20 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE GDR_OPORTUNIDAD_MEJORA (
    ID_OPORTUNIDAD_MEJORA NUMBER(19) NOT NULL,
    ID_RESULTADO NUMBER(19) NOT NULL,
    ID_ESTADO_OPORTUNIDAD_MEJORA NUMBER(19) NOT NULL,
    DESCRIPCION VARCHAR2(1000 CHAR) NOT NULL,
    RESPONSABLE VARCHAR2(180 CHAR) NOT NULL,
    PLAZO_COMPROMISO DATE NOT NULL,
    COMENTARIO_CIERRE VARCHAR2(1000 CHAR),
    USUARIO_REGISTRO VARCHAR2(120 CHAR) NOT NULL,
    FECHA_CIERRE TIMESTAMP(6),
    ESTADO_REGISTRO VARCHAR2(20 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE GDR_SEGUIMIENTO_OPORTUNIDAD_MEJORA (
    ID_SEGUIMIENTO_OPORTUNIDAD_MEJORA NUMBER(19) NOT NULL,
    ID_OPORTUNIDAD_MEJORA NUMBER(19) NOT NULL,
    COMENTARIO_SEGUIMIENTO VARCHAR2(1000 CHAR) NOT NULL,
    USUARIO_REGISTRO VARCHAR2(120 CHAR) NOT NULL,
    FECHA_REGISTRO TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_CREACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);
