WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

ALTER TABLE GDR_ESTADO_OPORTUNIDAD_MEJORA
    ADD CONSTRAINT PK_GDR_ESTADO_OPORTUNIDAD_MEJORA PRIMARY KEY (ID_ESTADO_OPORTUNIDAD_MEJORA);

ALTER TABLE GDR_OPORTUNIDAD_MEJORA
    ADD CONSTRAINT PK_GDR_OPORTUNIDAD_MEJORA PRIMARY KEY (ID_OPORTUNIDAD_MEJORA);

ALTER TABLE GDR_SEGUIMIENTO_OPORTUNIDAD_MEJORA
    ADD CONSTRAINT PK_GDR_SEGUIMIENTO_OPORTUNIDAD PRIMARY KEY (ID_SEGUIMIENTO_OPORTUNIDAD_MEJORA);

ALTER TABLE GDR_ESTADO_OPORTUNIDAD_MEJORA
    ADD CONSTRAINT UK_GDR_ESTADO_OPORTUNIDAD_CODIGO UNIQUE (CODIGO_ESTADO);

ALTER TABLE GDR_ESTADO_OPORTUNIDAD_MEJORA
    ADD CONSTRAINT CK_GDR_ESTADO_OPORTUNIDAD_REGISTRO
    CHECK (ESTADO_REGISTRO IN ('ACTIVO', 'INACTIVO'));

ALTER TABLE GDR_OPORTUNIDAD_MEJORA
    ADD CONSTRAINT CK_GDR_OPORTUNIDAD_REGISTRO
    CHECK (ESTADO_REGISTRO IN ('ACTIVO', 'INACTIVO'));

ALTER TABLE GDR_OPORTUNIDAD_MEJORA
    ADD CONSTRAINT FK_GDR_OPORTUNIDAD_RESULTADO
    FOREIGN KEY (ID_RESULTADO) REFERENCES GDR_RESULTADO (ID_RESULT);

ALTER TABLE GDR_OPORTUNIDAD_MEJORA
    ADD CONSTRAINT FK_GDR_OPORTUNIDAD_ESTADO
    FOREIGN KEY (ID_ESTADO_OPORTUNIDAD_MEJORA)
    REFERENCES GDR_ESTADO_OPORTUNIDAD_MEJORA (ID_ESTADO_OPORTUNIDAD_MEJORA);

ALTER TABLE GDR_SEGUIMIENTO_OPORTUNIDAD_MEJORA
    ADD CONSTRAINT FK_GDR_SEGUIMIENTO_OPORTUNIDAD
    FOREIGN KEY (ID_OPORTUNIDAD_MEJORA)
    REFERENCES GDR_OPORTUNIDAD_MEJORA (ID_OPORTUNIDAD_MEJORA);

CREATE INDEX IX_GDR_OPORTUNIDAD_RESULTADO ON GDR_OPORTUNIDAD_MEJORA (ID_RESULTADO);
CREATE INDEX IX_GDR_OPORTUNIDAD_ESTADO ON GDR_OPORTUNIDAD_MEJORA (ID_ESTADO_OPORTUNIDAD_MEJORA);
CREATE INDEX IX_GDR_OPORTUNIDAD_REGISTRO ON GDR_OPORTUNIDAD_MEJORA (ESTADO_REGISTRO);
CREATE INDEX IX_GDR_SEGUIMIENTO_OPORTUNIDAD ON GDR_SEGUIMIENTO_OPORTUNIDAD_MEJORA (ID_OPORTUNIDAD_MEJORA);
