WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

CREATE TABLE DOC_ESTADO_FLUJO_DOCUMENTAL (
    ID_ESTADO_FLUJO_DOCUMENTAL NUMBER(19) NOT NULL,
    CODIGO_ESTADO_FLUJO VARCHAR2(40 CHAR) NOT NULL,
    NOMBRE_ESTADO_FLUJO VARCHAR2(120 CHAR) NOT NULL,
    DESCRIPCION VARCHAR2(300 CHAR),
    ORDEN_FLUJO NUMBER(10) DEFAULT 0 NOT NULL,
    ESTADO_REGISTRO VARCHAR2(20 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE DOC_SOLICITUD_FIRMA (
    ID_SOLICITUD_FIRMA NUMBER(19) NOT NULL,
    ID_RESULTADO NUMBER(19) NOT NULL,
    ID_TIPO_DOCUMENTO NUMBER(19) NOT NULL,
    ID_PLANTILLA NUMBER(19) NOT NULL,
    ID_ESTADO_FLUJO_DOCUMENTAL NUMBER(19) NOT NULL,
    ID_DOCUMENTO_FIRMADO NUMBER(19),
    PROVEEDOR_FIRMA VARCHAR2(40 CHAR) NOT NULL,
    ID_TRANSACCION_EXTERNA VARCHAR2(120 CHAR),
    CLAVE_ARCHIVO_PREPARADO VARCHAR2(260 CHAR) NOT NULL,
    NOMBRE_ARCHIVO_PREPARADO VARCHAR2(180 CHAR) NOT NULL,
    MIME_TYPE_PREPARADO VARCHAR2(120 CHAR) NOT NULL,
    HASH_ARCHIVO_PREPARADO VARCHAR2(128 CHAR) NOT NULL,
    USUARIO_SOLICITUD VARCHAR2(120 CHAR),
    FECHA_SOLICITUD TIMESTAMP(6),
    FECHA_INICIO_FIRMA TIMESTAMP(6),
    FECHA_RETORNO TIMESTAMP(6),
    CODIGO_RESULTADO_FIRMA VARCHAR2(40 CHAR),
    MENSAJE_RESULTADO_FIRMA VARCHAR2(300 CHAR),
    ESTADO_REGISTRO VARCHAR2(20 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);
