WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

MERGE INTO SEC_ROLE target
USING (
    SELECT 'ADMIN' AS ROLE_CODE, 'Administrador' AS ROLE_NAME FROM DUAL
    UNION ALL
    SELECT 'OPERADOR' AS ROLE_CODE, 'Operador' AS ROLE_NAME FROM DUAL
    UNION ALL
    SELECT 'CONSULTA' AS ROLE_CODE, 'Consulta' AS ROLE_NAME FROM DUAL
) source
ON (target.ROLE_CODE = source.ROLE_CODE)
WHEN MATCHED THEN
    UPDATE SET
        target.ROLE_NAME = source.ROLE_NAME,
        target.STATUS = 'ACTIVE'
WHEN NOT MATCHED THEN
    INSERT (ID_ROLE, ROLE_CODE, ROLE_NAME, STATUS, CREATED_AT)
    VALUES (SQ_SEC_ROLE.NEXTVAL, source.ROLE_CODE, source.ROLE_NAME, 'ACTIVE', SYSTIMESTAMP);
