WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

ALTER TABLE DOC_SOLICITUD_FIRMA
    ADD (
        IND_FLUJO_ACTIVO CHAR(1) DEFAULT 'S' NOT NULL,
        FECHA_REGISTRO_DOCUMENTO TIMESTAMP(6)
    );

UPDATE DOC_SOLICITUD_FIRMA solicitud
SET
    IND_FLUJO_ACTIVO = CASE
        WHEN EXISTS (
            SELECT 1
            FROM DOC_ESTADO_FLUJO_DOCUMENTAL estado
            WHERE estado.ID_ESTADO_FLUJO_DOCUMENTAL = solicitud.ID_ESTADO_FLUJO_DOCUMENTAL
              AND estado.CODIGO_ESTADO_FLUJO IN ('LISTO_PARA_FIRMA', 'FIRMA_SOLICITADA', 'EN_FIRMA')
        )
        AND solicitud.ID_DOCUMENTO_FIRMADO IS NULL THEN 'S'
        ELSE 'N'
    END,
    FECHA_REGISTRO_DOCUMENTO = CASE
        WHEN solicitud.ID_DOCUMENTO_FIRMADO IS NOT NULL THEN NVL(solicitud.FECHA_RETORNO, solicitud.FECHA_ACTUALIZACION)
        ELSE solicitud.FECHA_REGISTRO_DOCUMENTO
    END;

ALTER TABLE DOC_SOLICITUD_FIRMA
    ADD CONSTRAINT CK_DOC_SOLICITUD_FLUJO_ACTIVO
    CHECK (IND_FLUJO_ACTIVO IN ('S', 'N'));

CREATE INDEX IX_DOC_SOLICITUD_FLUJO_ACTIVO
    ON DOC_SOLICITUD_FIRMA (IND_FLUJO_ACTIVO);

CREATE UNIQUE INDEX UX_DOC_SOLICITUD_FIRMA_FLUJO_ACTIVO
    ON DOC_SOLICITUD_FIRMA (
        DECODE(UPPER(ESTADO_REGISTRO), 'ACTIVO', DECODE(IND_FLUJO_ACTIVO, 'S', ID_RESULTADO, NULL), NULL),
        DECODE(UPPER(ESTADO_REGISTRO), 'ACTIVO', DECODE(IND_FLUJO_ACTIVO, 'S', ID_TIPO_DOCUMENTO, NULL), NULL)
    );
