WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

CREATE TABLE NOTIF_CANAL (
    ID_CANAL NUMBER(19) NOT NULL,
    CODIGO_CANAL VARCHAR2(40 CHAR) NOT NULL,
    NOMBRE_CANAL VARCHAR2(120 CHAR) NOT NULL,
    DESCRIPCION VARCHAR2(500 CHAR),
    ESTADO_REGISTRO VARCHAR2(20 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE NOTIF_PLANTILLA (
    ID_PLANTILLA_NOTIFICACION NUMBER(19) NOT NULL,
    CODIGO_PLANTILLA VARCHAR2(60 CHAR) NOT NULL,
    NOMBRE_PLANTILLA VARCHAR2(160 CHAR) NOT NULL,
    ASUNTO VARCHAR2(200 CHAR) NOT NULL,
    CUERPO_MENSAJE VARCHAR2(1000 CHAR) NOT NULL,
    ID_CANAL NUMBER(19) NOT NULL,
    VERSION_PLANTILLA NUMBER(10) DEFAULT 1 NOT NULL,
    ESTADO_REGISTRO VARCHAR2(20 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE NOTIF_NOTIFICACION (
    ID_NOTIFICACION NUMBER(19) NOT NULL,
    ID_USUARIO_DESTINO NUMBER(19) NOT NULL,
    ID_PLANTILLA_NOTIFICACION NUMBER(19) NOT NULL,
    CODIGO_EVENTO VARCHAR2(60 CHAR) NOT NULL,
    TITULO_NOTIFICACION VARCHAR2(200 CHAR) NOT NULL,
    MENSAJE_NOTIFICACION VARCHAR2(1000 CHAR) NOT NULL,
    ESTADO_NOTIFICACION VARCHAR2(20 CHAR) DEFAULT 'NO_LEIDA' NOT NULL,
    FECHA_ENVIO TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_LECTURA TIMESTAMP(6),
    REFERENCIA_NEGOCIO VARCHAR2(200 CHAR),
    ESTADO_REGISTRO VARCHAR2(20 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE CONSENT_TIPO (
    ID_TIPO_CONSENTIMIENTO NUMBER(19) NOT NULL,
    CODIGO_CONSENTIMIENTO VARCHAR2(60 CHAR) NOT NULL,
    NOMBRE_CONSENTIMIENTO VARCHAR2(180 CHAR) NOT NULL,
    TEXTO_CONSENTIMIENTO VARCHAR2(2000 CHAR) NOT NULL,
    VERSION_CONSENTIMIENTO NUMBER(10) DEFAULT 1 NOT NULL,
    REQUERIDO CHAR(1) DEFAULT 'N' NOT NULL,
    ESTADO_REGISTRO VARCHAR2(20 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE CONSENT_REGISTRO (
    ID_REGISTRO_CONSENTIMIENTO NUMBER(19) NOT NULL,
    ID_TIPO_CONSENTIMIENTO NUMBER(19) NOT NULL,
    ID_USUARIO NUMBER(19) NOT NULL,
    VERSION_CONSENTIMIENTO NUMBER(10) NOT NULL,
    IND_ACEPTADO CHAR(1) DEFAULT 'S' NOT NULL,
    FECHA_ACEPTACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    IP_ACEPTACION VARCHAR2(64 CHAR),
    USER_AGENT VARCHAR2(500 CHAR),
    DETALLE_ACEPTACION VARCHAR2(1000 CHAR),
    ESTADO_REGISTRO VARCHAR2(20 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);
