WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

ALTER TABLE SEC_USER
    ADD (ID_PERSON NUMBER(19));

UPDATE SEC_USER user_account
SET ID_PERSON = (
    SELECT MAX(person.ID_PERSON)
    FROM HR_PERSON person
    WHERE LOWER(person.EMAIL) = LOWER(user_account.EMAIL)
      AND UPPER(person.STATUS) = 'ACTIVE'
)
WHERE user_account.ID_PERSON IS NULL
  AND user_account.EMAIL IS NOT NULL
  AND (
      SELECT COUNT(*)
      FROM HR_PERSON person
      WHERE LOWER(person.EMAIL) = LOWER(user_account.EMAIL)
        AND UPPER(person.STATUS) = 'ACTIVE'
  ) = 1;

UPDATE SEC_USER user_account
SET ID_PERSON = (
    SELECT person.ID_PERSON
    FROM HR_PERSON person
    WHERE person.DOCUMENT_NUMBER = user_account.USERNAME
      AND UPPER(person.STATUS) = 'ACTIVE'
)
WHERE user_account.ID_PERSON IS NULL
  AND (
      SELECT COUNT(*)
      FROM HR_PERSON person
      WHERE person.DOCUMENT_NUMBER = user_account.USERNAME
        AND UPPER(person.STATUS) = 'ACTIVE'
  ) = 1;

ALTER TABLE SEC_USER
    ADD CONSTRAINT FK_SEC_USER_PERSON
    FOREIGN KEY (ID_PERSON) REFERENCES HR_PERSON (ID_PERSON);

ALTER TABLE SEC_USER
    ADD CONSTRAINT UK_SEC_USER_PERSON UNIQUE (ID_PERSON);

CREATE INDEX IX_SEC_USER_PERSON ON SEC_USER (ID_PERSON);
