WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

MERGE INTO SEC_ROLE target
USING (
    SELECT 'ADMIN_SISTEMA' AS ROLE_CODE, 'Administrador del sistema' AS ROLE_NAME FROM DUAL
    UNION ALL
    SELECT 'GDR_ORH' AS ROLE_CODE, 'ORH / RRHH GDR' AS ROLE_NAME FROM DUAL
    UNION ALL
    SELECT 'GDR_USUARIO' AS ROLE_CODE, 'Usuario GDR' AS ROLE_NAME FROM DUAL
    UNION ALL
    SELECT 'GDR_CONSULTA' AS ROLE_CODE, 'Consulta GDR' AS ROLE_NAME FROM DUAL
) source
ON (target.ROLE_CODE = source.ROLE_CODE)
WHEN MATCHED THEN
    UPDATE SET
        target.ROLE_NAME = source.ROLE_NAME,
        target.STATUS = 'ACTIVE'
WHEN NOT MATCHED THEN
    INSERT (ID_ROLE, ROLE_CODE, ROLE_NAME, STATUS, CREATED_AT)
    VALUES (SQ_SEC_ROLE.NEXTVAL, source.ROLE_CODE, source.ROLE_NAME, 'ACTIVE', SYSTIMESTAMP);

MERGE INTO SEC_USER_ROLE target
USING (
    SELECT
        user_account.ID_USER AS ID_USER,
        role_definition.ID_ROLE AS ID_ROLE
    FROM SEC_USER user_account
    JOIN SEC_ROLE role_definition
      ON role_definition.ROLE_CODE = 'ADMIN_SISTEMA'
    WHERE user_account.USERNAME = 'admin'
) source
ON (target.ID_USER = source.ID_USER AND target.ID_ROLE = source.ID_ROLE)
WHEN MATCHED THEN
    UPDATE SET
        target.STATUS = 'ACTIVE',
        target.ASSIGNED_AT = COALESCE(target.ASSIGNED_AT, SYSTIMESTAMP)
WHEN NOT MATCHED THEN
    INSERT (ID_USER_ROLE, ID_USER, ID_ROLE, STATUS, ASSIGNED_AT)
    VALUES (SQ_SEC_USER_ROLE.NEXTVAL, source.ID_USER, source.ID_ROLE, 'ACTIVE', SYSTIMESTAMP);
