WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

CREATE SEQUENCE SQ_GDR_SOLICITUD_MOD_META START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE GDR_SOLICITUD_MODIFICACION_META (
    ID_SOLICITUD_MODIFICACION_META NUMBER(19) NOT NULL,
    ID_GOAL NUMBER(19) NOT NULL,
    ID_ASSIGNMENT NUMBER(19) NOT NULL,
    ID_USUARIO_SOLICITANTE NUMBER(19) NOT NULL,
    USUARIO_SOLICITANTE VARCHAR2(60 CHAR) NOT NULL,
    CODIGO_TIPO_MODIFICACION VARCHAR2(40 CHAR) NOT NULL,
    MOTIVO_SOLICITUD VARCHAR2(1000 CHAR) NOT NULL,
    COMENTARIO_SOLICITUD VARCHAR2(1000 CHAR),
    CODIGO_ESTADO_SOLICITUD VARCHAR2(20 CHAR) DEFAULT 'PENDIENTE' NOT NULL,
    ESTADO_REGISTRO VARCHAR2(20 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    USUARIO_ACTUALIZACION VARCHAR2(60 CHAR) NOT NULL
);

ALTER TABLE GDR_SOLICITUD_MODIFICACION_META
    ADD CONSTRAINT PK_GDR_SOLICITUD_MOD_META PRIMARY KEY (ID_SOLICITUD_MODIFICACION_META);

ALTER TABLE GDR_SOLICITUD_MODIFICACION_META
    ADD CONSTRAINT FK_GDR_SOL_MOD_META_GOAL
    FOREIGN KEY (ID_GOAL) REFERENCES GDR_GOAL (ID_GOAL);

ALTER TABLE GDR_SOLICITUD_MODIFICACION_META
    ADD CONSTRAINT FK_GDR_SOL_MOD_META_ASSIGNMENT
    FOREIGN KEY (ID_ASSIGNMENT) REFERENCES GDR_EVALUATION_ASSIGNMENT (ID_ASSIGNMENT);

ALTER TABLE GDR_SOLICITUD_MODIFICACION_META
    ADD CONSTRAINT FK_GDR_SOL_MOD_META_USER
    FOREIGN KEY (ID_USUARIO_SOLICITANTE) REFERENCES SEC_USER (ID_USER);

ALTER TABLE GDR_SOLICITUD_MODIFICACION_META
    ADD CONSTRAINT CK_GDR_SOL_MOD_META_TIPO
    CHECK (CODIGO_TIPO_MODIFICACION IN ('TITULO', 'DESCRIPCION', 'INDICADOR', 'VALOR_ESPERADO', 'PESO', 'OTRO'));

ALTER TABLE GDR_SOLICITUD_MODIFICACION_META
    ADD CONSTRAINT CK_GDR_SOL_MOD_META_ESTADO
    CHECK (CODIGO_ESTADO_SOLICITUD IN ('PENDIENTE'));

ALTER TABLE GDR_SOLICITUD_MODIFICACION_META
    ADD CONSTRAINT CK_GDR_SOL_MOD_META_REGISTRO
    CHECK (ESTADO_REGISTRO IN ('ACTIVO', 'INACTIVO'));

CREATE INDEX IX_GDR_SOL_MOD_META_GOAL ON GDR_SOLICITUD_MODIFICACION_META (ID_GOAL);
CREATE INDEX IX_GDR_SOL_MOD_META_ASSIGNMENT ON GDR_SOLICITUD_MODIFICACION_META (ID_ASSIGNMENT);
CREATE INDEX IX_GDR_SOL_MOD_META_USER ON GDR_SOLICITUD_MODIFICACION_META (ID_USUARIO_SOLICITANTE);
CREATE INDEX IX_GDR_SOL_MOD_META_ESTADO ON GDR_SOLICITUD_MODIFICACION_META (CODIGO_ESTADO_SOLICITUD);
CREATE INDEX IX_GDR_SOL_MOD_META_FECHA ON GDR_SOLICITUD_MODIFICACION_META (FECHA_CREACION);

CREATE UNIQUE INDEX UX_GDR_SOL_MOD_META_PEND ON GDR_SOLICITUD_MODIFICACION_META (
    CASE WHEN CODIGO_ESTADO_SOLICITUD = 'PENDIENTE' AND ESTADO_REGISTRO = 'ACTIVO' THEN ID_GOAL END,
    CASE WHEN CODIGO_ESTADO_SOLICITUD = 'PENDIENTE' AND ESTADO_REGISTRO = 'ACTIVO' THEN ID_USUARIO_SOLICITANTE END,
    CASE WHEN CODIGO_ESTADO_SOLICITUD = 'PENDIENTE' AND ESTADO_REGISTRO = 'ACTIVO' THEN CODIGO_TIPO_MODIFICACION END
);
