WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

CREATE SEQUENCE SQ_GDR_ENVIO_META_ORH START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE GDR_ENVIO_META_ORH (
    ID_ENVIO_META_ORH NUMBER(19) NOT NULL,
    ID_GOAL NUMBER(19) NOT NULL,
    ID_ASSIGNMENT NUMBER(19) NOT NULL,
    ID_USUARIO_ENVIO NUMBER(19) NOT NULL,
    USUARIO_ENVIO VARCHAR2(60 CHAR) NOT NULL,
    ACTOR_FUNCIONAL_ENVIO VARCHAR2(40 CHAR) NOT NULL,
    COMENTARIO_ENVIO VARCHAR2(1000 CHAR),
    CODIGO_ESTADO_ENVIO VARCHAR2(20 CHAR) DEFAULT 'ENVIADO' NOT NULL,
    ESTADO_REGISTRO VARCHAR2(20 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_ENVIO TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_CREACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    USUARIO_ACTUALIZACION VARCHAR2(60 CHAR) NOT NULL
);

ALTER TABLE GDR_ENVIO_META_ORH
    ADD CONSTRAINT PK_GDR_ENVIO_META_ORH PRIMARY KEY (ID_ENVIO_META_ORH);

ALTER TABLE GDR_ENVIO_META_ORH
    ADD CONSTRAINT FK_GDR_ENV_META_ORH_GOAL
    FOREIGN KEY (ID_GOAL) REFERENCES GDR_GOAL (ID_GOAL);

ALTER TABLE GDR_ENVIO_META_ORH
    ADD CONSTRAINT FK_GDR_ENV_META_ORH_ASSIGNMENT
    FOREIGN KEY (ID_ASSIGNMENT) REFERENCES GDR_EVALUATION_ASSIGNMENT (ID_ASSIGNMENT);

ALTER TABLE GDR_ENVIO_META_ORH
    ADD CONSTRAINT FK_GDR_ENV_META_ORH_USER
    FOREIGN KEY (ID_USUARIO_ENVIO) REFERENCES SEC_USER (ID_USER);

ALTER TABLE GDR_ENVIO_META_ORH
    ADD CONSTRAINT CK_GDR_ENV_META_ORH_ESTADO
    CHECK (CODIGO_ESTADO_ENVIO IN ('ENVIADO'));

ALTER TABLE GDR_ENVIO_META_ORH
    ADD CONSTRAINT CK_GDR_ENV_META_ORH_REGISTRO
    CHECK (ESTADO_REGISTRO IN ('ACTIVO', 'INACTIVO'));

CREATE INDEX IX_GDR_ENV_META_ORH_GOAL ON GDR_ENVIO_META_ORH (ID_GOAL);
CREATE INDEX IX_GDR_ENV_META_ORH_ASSIGN ON GDR_ENVIO_META_ORH (ID_ASSIGNMENT);
CREATE INDEX IX_GDR_ENV_META_ORH_USER ON GDR_ENVIO_META_ORH (ID_USUARIO_ENVIO);
CREATE INDEX IX_GDR_ENV_META_ORH_ESTADO ON GDR_ENVIO_META_ORH (CODIGO_ESTADO_ENVIO);
CREATE INDEX IX_GDR_ENV_META_ORH_FECHA ON GDR_ENVIO_META_ORH (FECHA_ENVIO);

CREATE UNIQUE INDEX UX_GDR_ENV_META_ORH_ACT ON GDR_ENVIO_META_ORH (
    CASE WHEN CODIGO_ESTADO_ENVIO = 'ENVIADO' AND ESTADO_REGISTRO = 'ACTIVO' THEN ID_GOAL END
);
