WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

ALTER TABLE GDR_SOLICITUD_MODIFICACION_META ADD (
    FECHA_REVISION_ORH TIMESTAMP(6),
    ID_USUARIO_REVISION_ORH NUMBER(19),
    USUARIO_REVISION_ORH VARCHAR2(60 CHAR),
    COMENTARIO_REVISION_ORH VARCHAR2(1000 CHAR)
);

ALTER TABLE GDR_SOLICITUD_MODIFICACION_META
    DROP CONSTRAINT CK_GDR_SOL_MOD_META_ESTADO;

ALTER TABLE GDR_SOLICITUD_MODIFICACION_META
    ADD CONSTRAINT CK_GDR_SOL_MOD_META_ESTADO
    CHECK (CODIGO_ESTADO_SOLICITUD IN ('PENDIENTE', 'REVISADO'));

ALTER TABLE GDR_SOLICITUD_MODIFICACION_META
    ADD CONSTRAINT FK_GDR_SOL_MOD_META_USER_REV
    FOREIGN KEY (ID_USUARIO_REVISION_ORH) REFERENCES SEC_USER (ID_USER);

CREATE INDEX IX_GDR_SOL_MOD_META_USER_REV ON GDR_SOLICITUD_MODIFICACION_META (ID_USUARIO_REVISION_ORH);
CREATE INDEX IX_GDR_SOL_MOD_META_REV_FECHA ON GDR_SOLICITUD_MODIFICACION_META (FECHA_REVISION_ORH);

ALTER TABLE GDR_ENVIO_META_ORH ADD (
    FECHA_REVISION_ORH TIMESTAMP(6),
    ID_USUARIO_REVISION_ORH NUMBER(19),
    USUARIO_REVISION_ORH VARCHAR2(60 CHAR),
    COMENTARIO_REVISION_ORH VARCHAR2(1000 CHAR)
);

ALTER TABLE GDR_ENVIO_META_ORH
    DROP CONSTRAINT CK_GDR_ENV_META_ORH_ESTADO;

ALTER TABLE GDR_ENVIO_META_ORH
    ADD CONSTRAINT CK_GDR_ENV_META_ORH_ESTADO
    CHECK (CODIGO_ESTADO_ENVIO IN ('ENVIADO', 'REVISADO'));

ALTER TABLE GDR_ENVIO_META_ORH
    ADD CONSTRAINT FK_GDR_ENV_META_ORH_USER_REV
    FOREIGN KEY (ID_USUARIO_REVISION_ORH) REFERENCES SEC_USER (ID_USER);

CREATE INDEX IX_GDR_ENV_META_ORH_USER_REV ON GDR_ENVIO_META_ORH (ID_USUARIO_REVISION_ORH);
CREATE INDEX IX_GDR_ENV_META_ORH_REV_FECHA ON GDR_ENVIO_META_ORH (FECHA_REVISION_ORH);
