WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

ALTER TABLE GDR_GOAL ADD (
    FECHA_INICIO DATE,
    FECHA_FIN DATE
);

UPDATE GDR_GOAL g
SET (
    FECHA_INICIO,
    FECHA_FIN
) = (
    SELECT
        NVL(cycle.START_DATE, TRUNC(g.CREATED_AT)),
        CASE
            WHEN cycle.END_DATE IS NOT NULL
                 AND cycle.END_DATE >= NVL(cycle.START_DATE, TRUNC(g.CREATED_AT))
                THEN cycle.END_DATE
            ELSE NVL(cycle.START_DATE, TRUNC(g.CREATED_AT))
        END
    FROM GDR_EVALUATION_ASSIGNMENT assignment
    JOIN GDR_CYCLE cycle ON cycle.ID_CYCLE = assignment.ID_CYCLE
    WHERE assignment.ID_ASSIGNMENT = g.ID_ASSIGNMENT
)
WHERE g.FECHA_INICIO IS NULL
   OR g.FECHA_FIN IS NULL;

ALTER TABLE GDR_GOAL MODIFY (
    FECHA_INICIO NOT NULL,
    FECHA_FIN NOT NULL
);

ALTER TABLE GDR_GOAL
    ADD CONSTRAINT CK_GDR_GOAL_PLAZO
    CHECK (FECHA_INICIO <= FECHA_FIN);
