WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

ALTER TABLE GDR_EVIDENCIA ADD (
    CODIGO_TIPO_EVIDENCIA VARCHAR2(40 CHAR),
    CODIGO_FORMATO_ESPERADO VARCHAR2(40 CHAR)
);

UPDATE GDR_EVIDENCIA
SET CODIGO_TIPO_EVIDENCIA = 'AVANCE',
    CODIGO_FORMATO_ESPERADO = 'OTRO'
WHERE CODIGO_TIPO_EVIDENCIA IS NULL
   OR CODIGO_FORMATO_ESPERADO IS NULL;

ALTER TABLE GDR_EVIDENCIA MODIFY (
    CODIGO_TIPO_EVIDENCIA NOT NULL,
    CODIGO_FORMATO_ESPERADO NOT NULL
);

ALTER TABLE GDR_EVIDENCIA
    ADD CONSTRAINT CK_GDR_EVIDENCIA_TIPO
    CHECK (CODIGO_TIPO_EVIDENCIA IN ('AVANCE', 'FINAL'));

ALTER TABLE GDR_EVIDENCIA
    ADD CONSTRAINT CK_GDR_EVIDENCIA_FORMATO
    CHECK (CODIGO_FORMATO_ESPERADO IN ('IMAGEN', 'DOCUMENTO', 'ACTA', 'EXCEL', 'OTRO'));

CREATE INDEX IX_GDR_EVIDENCIA_TIPO ON GDR_EVIDENCIA (CODIGO_TIPO_EVIDENCIA);
CREATE INDEX IX_GDR_EVIDENCIA_FORMATO ON GDR_EVIDENCIA (CODIGO_FORMATO_ESPERADO);
