WHENEVER SQLERROR EXIT FAILURE ROLLBACK

ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;



ALTER TABLE GDR_REVISION_EVIDENCIA

    DROP CONSTRAINT CK_GDR_REVISION_EVIDENCIA_CALIFICACION;



ALTER TABLE GDR_REVISION_EVIDENCIA

    ADD CONSTRAINT CK_GDR_REVISION_EVIDENCIA_CALIFICACION

        CHECK (

            CODIGO_CALIFICACION_EVIDENCIA IS NULL

            OR CODIGO_CALIFICACION_EVIDENCIA IN (

                'LOGRADO',

                'EN_PROCESO_LOGRO',

                'NO_PRESENTA_EVIDENCIA',

                'PRESENTA_EVIDENCIA_FINAL',

                'NO_PRESENTA_EVIDENCIA_LOGRO_FINAL',

                'OBSERVADO'

            )

        );


