WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

ALTER TABLE GDR_GOAL ADD (
    ACHIEVED_VALUE NUMBER(18,4),
    CALCULATED_SCORE NUMBER(18,4)
);

ALTER TABLE GDR_GOAL ADD CONSTRAINT CK_GDR_GOAL_ACHIEVED_nonneg
    CHECK (ACHIEVED_VALUE IS NULL OR ACHIEVED_VALUE >= 0);

ALTER TABLE GDR_GOAL ADD CONSTRAINT CK_GDR_GOAL_SCORE_nonneg
    CHECK (CALCULATED_SCORE IS NULL OR CALCULATED_SCORE >= 0);
