WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

ALTER TABLE GDR_EVALUACION_FINAL ADD (
    QUALITATIVE_RATING_CODE VARCHAR2(40 CHAR)
);

ALTER TABLE GDR_EVALUACION_FINAL
    ADD CONSTRAINT CK_GDR_EVAL_QUAL_RATING
    CHECK (QUALITATIVE_RATING_CODE IS NULL OR QUALITATIVE_RATING_CODE IN (
        'BUEN_RENDIMIENTO',
        'SUJETO_OBSERVACION',
        'DISTINGUIDO',
        'DESAPROBADO',
        'NO_CALIFICABLE'
    ));

ALTER TABLE GDR_RESULTADO ADD (
    QUALITATIVE_RATING_CODE VARCHAR2(40 CHAR)
);

ALTER TABLE GDR_RESULTADO
    ADD CONSTRAINT CK_GDR_RESULT_QUAL_RATING
    CHECK (QUALITATIVE_RATING_CODE IS NULL OR QUALITATIVE_RATING_CODE IN (
        'BUEN_RENDIMIENTO',
        'SUJETO_OBSERVACION',
        'DISTINGUIDO',
        'DESAPROBADO',
        'NO_CALIFICABLE'
    ));
