WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

ALTER TABLE GDR_RESULTADO ADD (
    QUAL_RATING_NOTIFIED CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    DIRECTIVE_82_COMPLIANCE CHAR(1 CHAR) DEFAULT 'N' NOT NULL
);

ALTER TABLE GDR_RESULTADO
    ADD CONSTRAINT CK_GDR_RES_QUAL_NOTIFIED CHECK (QUAL_RATING_NOTIFIED IN ('Y', 'N'));

ALTER TABLE GDR_RESULTADO
    ADD CONSTRAINT CK_GDR_RES_DIRECTIVE82 CHECK (DIRECTIVE_82_COMPLIANCE IN ('Y', 'N'));

MERGE INTO SEC_ROLE target
USING (
    SELECT 'GDR_JUNTA_DIRECTIVOS' AS ROLE_CODE, 'Junta de Directivos GDR — cupo distinguido' AS ROLE_NAME FROM DUAL
) source
ON (target.ROLE_CODE = source.ROLE_CODE)
WHEN MATCHED THEN
    UPDATE SET
        target.ROLE_NAME = source.ROLE_NAME,
        target.STATUS = 'ACTIVE'
WHEN NOT MATCHED THEN
    INSERT (ID_ROLE, ROLE_CODE, ROLE_NAME, STATUS, CREATED_AT)
    VALUES (SQ_SEC_ROLE.NEXTVAL, source.ROLE_CODE, source.ROLE_NAME, 'ACTIVE', SYSTIMESTAMP);
