WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

ALTER TABLE GDR_CYCLE ADD (
    FINAL_EVAL_GRADE_START_DATE DATE,
    FINAL_EVAL_GRADE_END_DATE DATE,
    QUAL_NOTIFY_DEADLINE_DATE DATE
);

CREATE SEQUENCE SQ_GDR_PUBLIC_HOLIDAY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE GDR_PUBLIC_HOLIDAY (
    ID_PUBLIC_HOLIDAY NUMBER(19) NOT NULL,
    HOLIDAY_DATE DATE NOT NULL,
    DESCRIPTION VARCHAR2(200 CHAR),
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE GDR_PUBLIC_HOLIDAY ADD CONSTRAINT PK_GDR_PUBLIC_HOLIDAY PRIMARY KEY (ID_PUBLIC_HOLIDAY);

ALTER TABLE GDR_PUBLIC_HOLIDAY ADD CONSTRAINT UK_GDR_PUBLIC_HOLIDAY_DATE UNIQUE (HOLIDAY_DATE);

CREATE INDEX IX_GDR_PUBLIC_HOLIDAY_DATE ON GDR_PUBLIC_HOLIDAY (HOLIDAY_DATE);
