WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

ALTER TABLE GDR_EVIDENCIA ADD (
    FILE_KEY VARCHAR2(500 CHAR),
    FILE_ORIGINAL_NAME VARCHAR2(255 CHAR),
    FILE_MIME_TYPE VARCHAR2(120 CHAR),
    FILE_SIZE_BYTES NUMBER(19),
    FILE_UPLOADED_AT TIMESTAMP(6)
);

