WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

ALTER TABLE SEC_INSTITUTION_BRANDING ADD (
    NOMBRE_CORTO VARCHAR2(80 CHAR),
    RUC VARCHAR2(11 CHAR),
    DIRECCION VARCHAR2(300 CHAR),
    LOGO_RUTA VARCHAR2(500 CHAR),
    LOGO_MIME_TYPE VARCHAR2(100 CHAR),
    LOGO_NOMBRE_ORIGINAL VARCHAR2(255 CHAR)
);

ALTER TABLE SEC_INSTITUTION_BRANDING
    ADD CONSTRAINT CK_SEC_INST_BRANDING_LOGO_MIME_RUTA
    CHECK (
        LOGO_MIME_TYPE IS NULL
        OR LOGO_MIME_TYPE IN ('image/png', 'image/jpeg', 'image/webp', 'image/svg+xml')
    );

ALTER TABLE SEC_INSTITUTION_BRANDING
    ADD CONSTRAINT CK_SEC_INST_BRANDING_RUC
    CHECK (RUC IS NULL OR REGEXP_LIKE(RUC, '^[0-9]{11}$'));

ALTER TABLE SEC_INSTITUTION_BRANDING
    DROP CONSTRAINT CK_SEC_INST_BRANDING_MAIN_MIME;

ALTER TABLE SEC_INSTITUTION_BRANDING
    DROP CONSTRAINT CK_SEC_INST_BRANDING_HEADER_MIME;

ALTER TABLE SEC_INSTITUTION_BRANDING
    DROP (
        MAIN_LOGO,
        MAIN_LOGO_MIME_TYPE,
        HEADER_LOGO,
        HEADER_LOGO_MIME_TYPE
    );
