WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

-- V84: Crea tabla GDR_CRONOGRAMA — cronograma de etapas por ciclo
-- Normativa: RPE 068-2020-SERVIR-PE Art. 14 (cronograma del ciclo)
-- Una fila por etapa por ciclo. ORH define fechas; el sistema
-- calcula FECHA_FIN_NORMATIVA según la normativa vigente.

CREATE SEQUENCE SQ_GDR_CRONOGRAMA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE GDR_CRONOGRAMA (
    ID_CRONOGRAMA        NUMBER(19)    NOT NULL,
    ID_CICLO             NUMBER(19)    NOT NULL,
    ETAPA                VARCHAR2(50)  NOT NULL,
    FECHA_INICIO         DATE          NOT NULL,
    FECHA_FIN            DATE          NOT NULL,
    FECHA_FIN_NORMATIVA  DATE,
    ESTADO               VARCHAR2(30)  DEFAULT 'PENDIENTE' NOT NULL,
    CREATED_AT           TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL
) TABLESPACE TBS_GDR_DATA;

ALTER TABLE GDR_CRONOGRAMA ADD CONSTRAINT PK_GDR_CRONOGRAMA
    PRIMARY KEY (ID_CRONOGRAMA)
    USING INDEX TABLESPACE TBS_GDR_DATA;

ALTER TABLE GDR_CRONOGRAMA ADD CONSTRAINT FK_GDR_CRONOGRAMA_CICLO
    FOREIGN KEY (ID_CICLO) REFERENCES GDR_CYCLE (ID_CYCLE);

ALTER TABLE GDR_CRONOGRAMA ADD CONSTRAINT UK_GDR_CRONOGRAMA_CICLO_ETAPA
    UNIQUE (ID_CICLO, ETAPA)
    USING INDEX TABLESPACE TBS_GDR_DATA;

ALTER TABLE GDR_CRONOGRAMA ADD CONSTRAINT CK_GDR_CRONOGRAMA_ETAPA
    CHECK (ETAPA IN (
        'PLANIFICACION',
        'SEGUIMIENTO',
        'EVALUACION',
        'RETROALIMENTACION',
        'CONFIRMACION',
        'DISTINGUIDO',
        'CIERRE'
    ));

ALTER TABLE GDR_CRONOGRAMA ADD CONSTRAINT CK_GDR_CRONOGRAMA_ESTADO
    CHECK (ESTADO IN ('PENDIENTE', 'ACTIVA', 'COMPLETADA', 'VENCIDA'));

CREATE INDEX IX_GDR_CRONOGRAMA_CICLO ON GDR_CRONOGRAMA (ID_CICLO);
