WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

-- V85: Crea tabla GDR_SEGUIMIENTO — reuniones periódicas de seguimiento
-- Normativa: RPE 068-2020-SERVIR-PE Art. 26-32 (seguimiento mínimo 6 meses)
-- Una fila por reunión por par evaluador-evaluado.
-- VAL-01: fechaFin(SEGUIMIENTO) - fechaInicio(SEGUIMIENTO) >= 180 días

CREATE SEQUENCE SQ_GDR_SEGUIMIENTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE GDR_SEGUIMIENTO (
    ID_SEGUIMIENTO          NUMBER(19)      NOT NULL,
    ID_ASSIGNMENT           NUMBER(19)      NOT NULL,
    ID_CICLO                NUMBER(19)      NOT NULL,
    TIPO_REUNION            VARCHAR2(50)    DEFAULT 'SEGUIMIENTO_PERIODICO' NOT NULL,
    FECHA_REUNION           DATE            NOT NULL,
    DESCRIPCION_AVANCE      VARCHAR2(2000),
    COMPROMISOS             VARCHAR2(2000),
    ESTADO                  VARCHAR2(30)    DEFAULT 'REALIZADA' NOT NULL,
    ID_EVALUADOR            NUMBER(19),
    ID_EVALUADO             NUMBER(19),
    CONSENTIMIENTO_EVALUADO NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_AT              TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL
) TABLESPACE TBS_GDR_DATA;

ALTER TABLE GDR_SEGUIMIENTO ADD CONSTRAINT PK_GDR_SEGUIMIENTO
    PRIMARY KEY (ID_SEGUIMIENTO)
    USING INDEX TABLESPACE TBS_GDR_DATA;

ALTER TABLE GDR_SEGUIMIENTO ADD CONSTRAINT FK_GDR_SEGUIM_ASSIGNMENT
    FOREIGN KEY (ID_ASSIGNMENT) REFERENCES GDR_EVALUATION_ASSIGNMENT (ID_ASSIGNMENT);

ALTER TABLE GDR_SEGUIMIENTO ADD CONSTRAINT FK_GDR_SEGUIM_CICLO
    FOREIGN KEY (ID_CICLO) REFERENCES GDR_CYCLE (ID_CYCLE);

ALTER TABLE GDR_SEGUIMIENTO ADD CONSTRAINT FK_GDR_SEGUIM_EVALUADOR
    FOREIGN KEY (ID_EVALUADOR) REFERENCES SEC_USER (ID_USER);

ALTER TABLE GDR_SEGUIMIENTO ADD CONSTRAINT FK_GDR_SEGUIM_EVALUADO
    FOREIGN KEY (ID_EVALUADO) REFERENCES SEC_USER (ID_USER);

ALTER TABLE GDR_SEGUIMIENTO ADD CONSTRAINT CK_GDR_SEGUIM_TIPO
    CHECK (TIPO_REUNION IN (
        'SEGUIMIENTO_PERIODICO',
        'RETROALIMENTACION_PERIODICA'
    ));

ALTER TABLE GDR_SEGUIMIENTO ADD CONSTRAINT CK_GDR_SEGUIM_ESTADO
    CHECK (ESTADO IN ('REALIZADA', 'PENDIENTE_CONSENTIMIENTO', 'CONFIRMADA', 'ANULADA'));

ALTER TABLE GDR_SEGUIMIENTO ADD CONSTRAINT CK_GDR_SEGUIM_CONSENT
    CHECK (CONSENTIMIENTO_EVALUADO IN (0, 1));

CREATE INDEX IX_GDR_SEGUIM_ASSIGNMENT
    ON GDR_SEGUIMIENTO (ID_ASSIGNMENT)
    TABLESPACE TBS_GDR_DATA;

CREATE INDEX IX_GDR_SEGUIM_CICLO
    ON GDR_SEGUIMIENTO (ID_CICLO)
    TABLESPACE TBS_GDR_DATA;
