-- ============================================================================
-- V87 - GDR_SOLICITUD_CONFIRMACION (P4)
-- Solicitud de confirmacion de calificacion presentada por el evaluado.
-- Normativa: RPE 068-2020-SERVIR-PE Art. 41 (plazo: 5 dias habiles desde la
-- reunion de retroalimentacion final, ya persistido en GDR_EVALUACION_FINAL).
-- Tablespace: TBS_GDR_DATA (el DEFAULT del usuario apunta a TBS_RRHH inexistente).
-- ============================================================================

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
    FROM user_sequences
   WHERE sequence_name = 'SQ_GDR_SOLICITUD_CONF';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SQ_GDR_SOLICITUD_CONF START WITH 1 INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

CREATE TABLE GDR_SOLICITUD_CONFIRMACION (
  ID_SOLICITUD          NUMBER(19)          NOT NULL,
  ID_FINAL_EVALUATION   NUMBER(19)          NOT NULL,
  ID_EVALUADO           NUMBER(19)          NOT NULL,
  ID_CICLO              NUMBER(19)          NOT NULL,
  FECHA_SOLICITUD       TIMESTAMP           NOT NULL,
  SUSTENTO_EVALUADO     VARCHAR2(2000 CHAR) NOT NULL,
  ESTADO                VARCHAR2(30)        DEFAULT 'PRESENTADA' NOT NULL,
  FECHA_DERIVACION_CIE  TIMESTAMP,
  CREATED_AT            TIMESTAMP           NOT NULL,
  UPDATED_AT            TIMESTAMP           NOT NULL,
  CONSTRAINT PK_GDR_SOLICITUD_CONF PRIMARY KEY (ID_SOLICITUD)
    USING INDEX TABLESPACE TBS_GDR_DATA,
  CONSTRAINT UK_GDR_SOLCONF_EVALUACION UNIQUE (ID_FINAL_EVALUATION)
    USING INDEX TABLESPACE TBS_GDR_DATA,
  CONSTRAINT FK_GDR_SOLCONF_EVALUACION FOREIGN KEY (ID_FINAL_EVALUATION)
    REFERENCES GDR_EVALUACION_FINAL (ID_FINAL_EVALUATION),
  CONSTRAINT FK_GDR_SOLCONF_EVALUADO FOREIGN KEY (ID_EVALUADO)
    REFERENCES HR_PERSON (ID_PERSON),
  CONSTRAINT FK_GDR_SOLCONF_CICLO FOREIGN KEY (ID_CICLO)
    REFERENCES GDR_CYCLE (ID_CYCLE),
  CONSTRAINT CK_GDR_SOLCONF_ESTADO CHECK (ESTADO IN ('PRESENTADA', 'EN_CIE', 'RESUELTA'))
) TABLESPACE TBS_GDR_DATA;

CREATE INDEX IX_GDR_SOLCONF_EVALUADO ON GDR_SOLICITUD_CONFIRMACION (ID_EVALUADO)
  TABLESPACE TBS_GDR_DATA;
CREATE INDEX IX_GDR_SOLCONF_CICLO ON GDR_SOLICITUD_CONFIRMACION (ID_CICLO)
  TABLESPACE TBS_GDR_DATA;
CREATE INDEX IX_GDR_SOLCONF_ESTADO ON GDR_SOLICITUD_CONFIRMACION (ESTADO)
  TABLESPACE TBS_GDR_DATA;

COMMENT ON TABLE GDR_SOLICITUD_CONFIRMACION IS
  'Solicitud de confirmacion de calificacion presentada por el evaluado (RPE 068-2020 Art. 41).';
COMMENT ON COLUMN GDR_SOLICITUD_CONFIRMACION.SUSTENTO_EVALUADO IS
  'Sustento escrito del evaluado para solicitar la confirmacion de su calificacion.';
COMMENT ON COLUMN GDR_SOLICITUD_CONFIRMACION.ESTADO IS
  'PRESENTADA -> EN_CIE -> RESUELTA.';
