-- ============================================================================
-- V92 - GDR_INFORME_CIERRE (P7)
-- Informe de cierre del ciclo GDR — RPE 068-2020-SERVIR-PE Art. 55
-- Tablespace: TBS_GDR_DATA
-- ============================================================================
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
ALTER SESSION SET CURRENT_SCHEMA = &&APP_DB_SCHEMA;

DECLARE v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_sequences WHERE sequence_name = 'SQ_GDR_INFORME_CIERRE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SQ_GDR_INFORME_CIERRE START WITH 1 INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

CREATE TABLE GDR_INFORME_CIERRE (
  ID_INFORME_CIERRE              NUMBER(19)       NOT NULL,
  ID_CICLO                       NUMBER(19)       NOT NULL,
  ESTADO                         VARCHAR2(30)     DEFAULT 'BORRADOR' NOT NULL,
  TOTAL_EVALUADOS                NUMBER(10)       DEFAULT 0 NOT NULL,
  TOTAL_BUEN_RENDIMIENTO         NUMBER(10)       DEFAULT 0 NOT NULL,
  TOTAL_SUJETO_OBSERVACION       NUMBER(10)       DEFAULT 0 NOT NULL,
  TOTAL_DESAPROBADO              NUMBER(10)       DEFAULT 0 NOT NULL,
  TOTAL_DISTINGUIDO              NUMBER(10)       DEFAULT 0 NOT NULL,
  TOTAL_OPORTUNIDADES_MEJORA     NUMBER(10)       DEFAULT 0 NOT NULL,
  TOTAL_CONFIRMACIONES           NUMBER(10)       DEFAULT 0 NOT NULL,
  TOTAL_CONFIRMACIONES_RESUELTAS NUMBER(10)     DEFAULT 0 NOT NULL,
  TOTAL_DOCUMENTOS_FIRMADOS      NUMBER(10)       DEFAULT 0 NOT NULL,
  OBSERVACIONES_ORH              VARCHAR2(4000),
  GENERADO_POR                   VARCHAR2(120)    NOT NULL,
  FECHA_GENERACION               TIMESTAMP(6)     NOT NULL,
  CREATED_AT                     TIMESTAMP(6)     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT                     TIMESTAMP(6)     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_GDR_INFORME_CIERRE PRIMARY KEY (ID_INFORME_CIERRE)
    USING INDEX TABLESPACE TBS_GDR_DATA
) TABLESPACE TBS_GDR_DATA;

ALTER TABLE GDR_INFORME_CIERRE ADD CONSTRAINT FK_GDR_INFCICLO_CICLO
    FOREIGN KEY (ID_CICLO) REFERENCES GDR_CYCLE (ID_CYCLE);

ALTER TABLE GDR_INFORME_CIERRE ADD CONSTRAINT CK_GDR_INFCICLO_ESTADO
    CHECK (ESTADO IN ('BORRADOR', 'VALIDADO', 'REMITIDO'));

CREATE INDEX IX_GDR_INFCICLO_CICLO ON GDR_INFORME_CIERRE (ID_CICLO, FECHA_GENERACION DESC)
    TABLESPACE TBS_GDR_DATA;

COMMENT ON TABLE GDR_INFORME_CIERRE IS 'Informe de cierre del ciclo GDR (RPE 068-2020 Art. 55).';

COMMIT;
