CREATE SEQUENCE SQ_GDR_PARTICIPANT START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE GDR_PARTICIPANT (
    ID_PARTICIPANT NUMBER(19, 0) NOT NULL,
    ID_CYCLE NUMBER(19, 0) NOT NULL,
    ID_PERSON NUMBER(19, 0) NOT NULL,
    ROLE VARCHAR2(20 CHAR) NOT NULL,
    STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_GDR_PARTICIPANT PRIMARY KEY (ID_PARTICIPANT),
    CONSTRAINT FK_PARTICIPANT_CYCLE FOREIGN KEY (ID_CYCLE) REFERENCES GDR_ACTIVE_CYCLE (ID_CYCLE),
    CONSTRAINT FK_PARTICIPANT_PERSON FOREIGN KEY (ID_PERSON) REFERENCES HR_PERSON (ID_PERSON),
    CONSTRAINT UQ_PARTICIPANT_CYCLE_PERSON UNIQUE (ID_CYCLE, ID_PERSON)
);

CREATE INDEX IDX_PARTICIPANT_CYCLE ON GDR_PARTICIPANT(ID_CYCLE);
CREATE INDEX IDX_PARTICIPANT_ROLE ON GDR_PARTICIPANT(ROLE);
